const config = {
  challenge: true, // Set to true if you want to enable password protection.
  users: {
    // You can add multiple users by doing username: 'password'.
    asher: 'aaa',
    tenzin: 'ttt',
    geronimo: 'ggg',
    ben: 'bbb',
    vivian: 'vvv',
    job: 'jjj',
     eric: 'eee',
    dawson: 'ddd',
    johnny: 'jjj',
    jacob: 'jjj',
    joe: 'jjj',
    max: 'mmm',
    justin: 'jjj',
    olivia: 'ooo',
    hudson: 'hhh',
    scott: 'sss',
    peter: 'ppp',
    connor: 'ccc',
    ant: 'aaa',
    tyrone: 'ttt',
    brennan: 'bbb',
    julian: 'jjj',
    alek: 'aaa',
    quincy: 'qqq',
    nova: 'nnn',
    alex: 'aaa',
    nick: 'nnn',
    ns: 'ns',
    caiden: 'ccc',
    john: 'jjj',
    Skibidi: 'Toilet',
    dario: 'Insano 12th!',
    Toxictomb: 'Sunita/2011',
    eliteowen03: 'owenwiener10',
    MaoriMenace: '.',
    DylanPlayzgfnf: 'ddd',
    gyattmaxer: 'ggg',
    chillguy: 'ccc',
    WhosJay11: 'jjj',    
    oopa_91: 'ddd',
    hi: 'j',
    guyontheinternet0234: 'Rnstn2641hamburger',
    magog2k: '123454321',
    Tristan: 'ttt',
    aedoti: 'Abcdefg!!',
    peepeeman69420: 'peepeeman69420',
    Bruh: 'SussyBoy0',

  },
  routes: true, // Change this to false if you just want to host a bare server.
  local: true, // Change this to false to disable local assets.
}
export default config
